AllCops:
  NewCops: enable

Naming/FileName:
  Exclude:
    - lib/cassandra-record.rb

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Security/Eval:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/Alias:
  Enabled: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Lint/UnusedMethodArgument:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/OptionalArguments:
  Enabled: false
