
rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1

jdk:
  - oraclejdk8

install:
  - travis_retry bundle install
  - curl -s http://artfiles.org/apache.org/cassandra/3.9/apache-cassandra-3.9-bin.tar.gz | tar xz -C /tmp
  - MAX_HEAP_SIZE=128M HEAP_NEWSIZE=32M /tmp/apache-cassandra-3.9/bin/cassandra

before_script:
  - sleep 20

script:
  - bundle exec rake test

sudo: false

